portfolio/candidate/urls.py
# Third Party Library
from candidate.views import index, render_education_certificate
from django.urls import path

app_name = "candidate"

urlpatterns = [
    path("", index, name="index"),
    path(
        "candidate/certificate",
        render_education_certificate,
        name="certificate",
    ),
]

portfolio/portfolio/urls.py
# Third Party Library
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from candidate.admin import custom_admin_site

urlpatterns = [
    path("admin/", custom_admin_site.urls),
] + i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("candidate.urls", namespace="project")),
    prefix_default_language=False,
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

portfolio/candidate/models.py
# Standard Library
import re

# Third Party Library
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import F, Q
from django.utils.translation import gettext_lazy as _


class Candidate(models.Model):
    """Модель пользователя."""

    class SearchStatus(models.TextChoices):
        ACTIVE = "Active", _("In active search")
        ADVANCED = "Passive", _("Open to opportunities")
        INACTIVE = "Inactive", _("Not looking for a job")

    title = models.CharField(_("Title"), max_length=200, default="candidate")
    name = models.CharField(_("Name"), max_length=200)
    surname = models.CharField(_("Surname"), max_length=200)
    image = models.ImageField(
        _("Image"), upload_to="user_image/", blank=True, null=True
    )
    search_job_title = models.CharField(
        _("What job the candidate wants to find"),
        max_length=200,
        blank=True,
        null=True,
    )
    email = models.EmailField("Email", max_length=254, unique=True)
    distant_work = models.BooleanField(_("Ready for remote job"), default=True)
    ready_to_relocate = models.BooleanField(
        _("Ready to relocate"), default=False
    )
    job_search_status = models.CharField(
        _("Job search status"),
        max_length=100,
        choices=SearchStatus.choices,
        default=SearchStatus.ACTIVE,
    )

    phone_num = models.CharField(
        _("Phone number"), max_length=12, blank=True, null=True
    )
    city = models.CharField(_("City"), max_length=200, blank=True, null=True)
    country = models.CharField(
        _("Country"), max_length=200, blank=True, null=True
    )
    about = models.TextField(_("About candidate"), blank=True, null=True)
    about_skills = models.TextField(
        _("About candidate's skills"), blank=True, null=True
    )
    telegram = models.URLField(_("Telegram link"), blank=True, null=True)
    linkedin = models.URLField(_("Linkedin link"), blank=True, null=True)
    github = models.URLField(_("Github link"), blank=True, null=True)
    stack_overflow = models.URLField(
        _("Stack Overflow link"), blank=True, null=True
    )
    codeopen = models.URLField(_("Codeopen link"), blank=True, null=True)

    is_chosen_candidate = models.BooleanField(
        _("Chosen candidate"),
        default=True,
    )

    class Meta:
        constraints = [
            models.constraints.UniqueConstraint(
                fields=["is_chosen_candidate"],
                condition=Q(is_chosen_candidate=True),
                name="unique_is_chosen_candidate",
            )
        ]

    def __str__(self):
        return f"{self.name} {self.surname} - {self.title}"


class Job(models.Model):
    candidate = models.ManyToManyField(
        Candidate,
        verbose_name=_("Candidate"),
        related_name="jobs",
    )
    title = models.CharField(_("Title"), max_length=200)
    description = models.TextField(_("Description"))
    company = models.CharField(_("Company name"), max_length=200)
    company_link = models.URLField(_("Company's website url"))
    date_from = models.DateField(_("Date from"))
    date_to = models.DateField(_("Date to"), blank=True, null=True)

    class Meta:
        ordering = [F("date_to").desc(nulls_first=True), "-date_from"]

    def __str__(self):
        return self.title


class Skill(models.Model):
    title = models.CharField(_("Title"), max_length=200)
    percent = models.PositiveSmallIntegerField(
        _("Percentage"),
        validators=[MaxValueValidator(100), MinValueValidator(1)],
    )

    class Meta:
        ordering = ("-percent",)
        abstract = True

    def __str__(self):
        return self.title


class HardSkill(Skill):
    class Level(models.TextChoices):
        GOOD = "Good", _("Good")
        ADVANCED = "Advanced", _("Advanced")
        EXPERT = "Expert", _("Expert")
        PRO = "Pro", _("Pro")

    candidate = models.ManyToManyField(
        Candidate,
        verbose_name=_("Candidate"),
        related_name="hard_skills",
    )
    level = models.CharField(_("Level"), max_length=100, choices=Level.choices)

    class Meta(Skill.Meta):
        abstract = False


class SoftSkill(Skill):
    candidate = models.ManyToManyField(
        Candidate,
        verbose_name=_("Candidate"),
        related_name="soft_skills",
    )

    class Meta(Skill.Meta):
        abstract = False


class Education(models.Model):
    candidate = models.ManyToManyField(
        Candidate,
        verbose_name=_("Candidate"),
        related_name="educations",
    )
    title = models.CharField(_("Title"), max_length=200)
    place = models.CharField(_("Institution name"), max_length=200)
    date_from = models.DateField(_("Date from"))
    date_to = models.DateField(_("Date to"), blank=True, null=True)
    image = models.FileField(
        _("Certificate"), upload_to="certificate/", blank=True, null=True
    )

    def __str__(self):
        return self.title


class Language(models.Model):
    class Stars(models.TextChoices):
        ONE = "0", _("One star")
        TWO = "01", _("Two stars")
        THREE = "012", _("Three stars")
        FOUR = "0123", _("Four stars")
        FIVE = "01234", _("Five stars")

    candidate = models.ManyToManyField(
        Candidate,
        verbose_name=_("Candidate"),
        related_name="languages",
    )
    title = models.CharField(_("Title"), max_length=200)
    level = models.CharField(_("Level"), max_length=200)
    stars = models.CharField(_("Extent"), max_length=5, choices=Stars.choices)

    def __str__(self):
        return self.title


class Recomendation(models.Model):
    candidate = models.ManyToManyField(
        Candidate,
        verbose_name=_("Candidate"),
        related_name="recomendations",
    )
    text = models.TextField(_("Text"))
    author = models.CharField(_("Author"), max_length=200)
    author_job_title = models.CharField(
        _("Author's job title"), max_length=200
    )

    def __str__(self):
        return self.author


class OtherProject(models.Model):
    candidate = models.ManyToManyField(
        Candidate,
        verbose_name=_("Candidate"),
        related_name="other_projects",
    )
    title = models.CharField(_("Title"), max_length=200)
    description = models.TextField(_("Description"))
    github_link = models.URLField(_("Github link"))
    finish_date = models.DateField(_("Project end date"))

    class Meta:
        ordering = ("-finish_date",)

    def __str__(self):
        return self.title


class Project(models.Model):
    candidate = models.ManyToManyField(
        Candidate,
        verbose_name=_("Candidate"),
        related_name="projects",
    )
    image = models.ImageField(_("Preview"), upload_to="previews/")
    online_link = models.URLField(_("Link"))
    title = models.CharField(_("Title"), max_length=200)
    description = models.TextField(
        _("Description"),
        help_text=_(
            "General description in one sentence, key goal, "
            "what you've implemented in the project. 3-4 santances"
        ),
    )
    github_link = models.URLField(_("Github link"))
    finish_date = models.DateField(_("Project end date"))
    stack = models.ManyToManyField(
        "Stack",
        verbose_name=_("Stack"),
        related_name="projects",
    )

    class Meta:
        ordering = ("-finish_date",)

    def __str__(self):
        return self.title


class File(models.Model):
    """
    Model for storing candidates files such as CV
    or something of that kind.
    """

    candidate = models.ForeignKey(
        Candidate,
        verbose_name=_("Candidate"),
        on_delete=models.CASCADE,
        related_name="files",
    )
    image = models.FileField(
        _("File"),
        upload_to="files/",
    )
    title = models.CharField(_("Title"), max_length=200)
    description = models.TextField(_("Description"), blank=True, null=True)
    change_date = models.DateTimeField(_("Change date"), auto_now=True)

    class Meta:
        ordering = ("-change_date",)

    def __str__(self):
        return self.title


class Stack(models.Model):
    title = models.CharField(_("Title"), max_length=30, unique=True)

    def __str__(self) -> str:
        return self.title


class Ip(models.Model):
    ip = models.GenericIPAddressField("IP")
    view_datetime = models.DateTimeField(_("View datetime"), auto_now_add=True)
    candidate = models.ForeignKey(
        Candidate,
        verbose_name=_("Candidate"),
        on_delete=models.SET_NULL,
        null=True,
        related_name="ips",
    )

    def __str__(self):
        return self.ip

portfolio/templates/includes/footer.html
<footer class="footer">
    <div class="container text-center">
        <!--/* This template is free as long as you keep the attribution link below. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
        <small class="copyright">
            Designed with
            <span class="sr-only">love</span>
            <i class="fas fa-heart"></i>
            by
            <a href="https://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a>
            for developers.
            <a href="https://github.com/xriley/Developer-Theme" target="_blank">GitHub</a> 
        </small>
    </div>
    <!--//container-->
</footer>
<!--//footer-->

portfolio/templates/includes/header.html
{% load static %}
{% load i18n %}
{% load thumbnail %}
<header class="header">
    <div class="container">
        <div class="row align-items-center justify-content-between">
            <div class="col     ">
                <div class="col-12 col-lg-auto">
                    {% thumbnail candidate.image "180x180" crop="center" upscale=False quality=100 as im %}
                        <img class="profile-image img-fluid float-start rounded-circle" src={{ im.url }} alt="profile image" />
                    {% endthumbnail %}
                </div>
                <div class="col-12 col-lg-auto">
                    <div class="profile-content">
                        <h1 class="name">{{ candidate.name }} {{ candidate.surname }}</h1>
                        <h2 class="desc">{{ candidate.search_job_title }} - {{ candidate.get_job_search_status_display }}</h2>
                        <ul class="list-unstyled">
                            {% if candidate.ready_to_relocate %}
                                <li>{% trans "Ready to relocate" %}</li>
                            {% else %}
                                <li>{% trans "Not ready to relocate" %}</li>
                            {% endif %}
                            {% if candidate.distant_work %}
                                <li>{% trans "Ready for remote job" %}</li>
                            {% else %}
                                <li>{% trans "Not ready for remote job" %}</li>
                            {% endif %}
                        </ul>
                        <ul class="social list-inline">
                            {% if candidate.telegram %}
                                <li class="list-inline-item">
                                    <a href={{ candidate.telegram }} target="_blank"><i class="fab fa-telegram"></i></a>
                                </li>
                            {% endif %}
                            {% if candidate.linkedin %}
                                <li class="list-inline-item">
                                    <a href={{ candidate.linkedin }} target="_blank"><i class="fab fa-linkedin-in"></i></a>
                                </li>
                            {% endif %}
                            {% if candidate.github %}
                                <li class="list-inline-item">
                                    <a href={{ candidate.github }} target="_blank"><i class="fab fa-github-alt"></i></a>
                                </li>
                            {% endif %}
                            {% if candidate.stack_overflow %}
                                <li class="list-inline-item">
                                    <a href={{ candidate.stack_overflow }} target="_blank"><i class="fab fa-stack-overflow"></i></a>
                                </li>
                            {% endif %}
                            {% if candidate.codeopen %}
                                <li class="list-inline-item last-item">
                                    <a href={{ candidate.codeopen }} target="_blank"><i class="fab fa-codepen"></i></a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-auto">
                <div class="dark-mode-switch d-flex">
                    <div class="form-check form-switch mx-auto mx-lg-0">
                        <input type="checkbox" class="form-check-input me-2" id="darkSwitch" />
                        <label class="custom-control-label" for="darkSwitch">{% trans "Dark Mode" %}</label>
                    </div>
                </div>
                <!--//dark-mode-switch-->
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <button class="btn btn-cta-primary"
                                name="language"
                                type="submit"
                                value="{{ language.code }}"
                                {% if language.code == LANGUAGE_CODE %}disabled{% endif %}>{{ language.code }}</button>
                    {% endfor %}
                </form>
                <a class="btn btn-cta-primary" href={{ candidate.telegram }} target="_blank">
                    <i class="fas fa-paper-plane"></i>
                    {% trans "Contact me" %}
                </a>
            </div>
            <!--//col-->
        </div>
        <!--//row-->
    </div>
    <!--//container-->
</header>
<!--//header-->

portfolio/templates/includes/load_more_button.html
{% load i18n %}
<div class="d-flex justify-content-center">
    <button class="btn btn-cta-secondary load-more-button">{% trans "Load More" %}</button>
</div>

portfolio/templates/includes/pdf_modal.html
<!-- Modal -->
{% load i18n %}
<div class="modal modal-lg fade"
     id="eduationModal"
     tabindex="-1"
     role="dialog"
     aria-labelledby="eduationModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-fullscreen p-5"
         role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="eduationModalLabel">{% trans "Certificate" %}</h5>
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-body-id"></div>
        </div>
    </div>
</div>